### ISSUE TITLE
16GB is not enough to run qrcode v2v animatediff , do I need to upgrade the hardware configuration?

### ISSUE THREAD

**Issue by hylarucoder** [nerdyrodent/AVeryComfyNerd#10]
Can you please tell me your hardware configuration?

**Comment by nerdyrodent** [comment]
I'm using a 3090, but the workflow needs around 14GB VRAM by default. You can, of course, set the scale down to a smaller size to use less VRAM.

**Comment by nerdyrodent** [comment]
![Screenshot from 2023-10-22 12-51-17](https://github.com/nerdyrodent/AVeryComfyNerd/assets/74688049/130ffa68-aaf1-4c02-a0b3-8b4dd55a7147)
