### ISSUE TITLE
Groudingdino and Segment anything error

### ISSUE THREAD

**Issue by GoDJr** [nerdyrodent/AVeryComfyNerd#11]
Im getting the following error was wondering if any of you guys had encountered it or can help cause I'm having a hard time finding a solution.

Error occurred when executing GroundingDinoSAMSegment (segment anything): upper bound and larger bound inconsistent with step sign

terminal shows me this:
groundingdino/models/GroundingDINO/bertwarper.py", line 252, in generate_masks_with_special_tokens_and_transfer_map
position_ids[row, previous_col + 1 : col + 1] = torch.arange(
^^^^^^^^^^^^^
RuntimeError: upper bound and larger bound inconsistent with step sign

Im trying to use the reposer plus workflow posted. im running comfyui with --force-fp16 on an Intel mac pro 2019 with a AMD Radeon Pro 580X 8 GB and 48 gb of ram.

**Comment by nerdyrodent** [comment]
The "segment anything" custom node page is at - https://github.com/storyicon/comfyui_segment_anything
