### ISSUE TITLE
loading base model/unload clone 2

### ISSUE THREAD

**Issue by stuver0** [nerdyrodent/AVeryComfyNerd#12]
Hi, love the work you've been putting in. My PC seems to linger on the unloading of a model:

[AnimateDiffEvo] - INFO - Injecting motion module mm_sd_v15_v2.ckpt version v2.
Requested to load BaseModel
Loading 1 new model
unload clone 2

Is it normal that that takes so long?

cheers

**Comment by nerdyrodent** [comment]
Can't say I've noticed! The custom node developer may know more though
