### ISSUE TITLE
Recently getting the error 'ClipVisionModel' object has no attribute 'processor'

### ISSUE THREAD

**Issue by KINGLIFER** [nerdyrodent/AVeryComfyNerd#15]
used to work days before. updated comfyUi.

File "D:\Ai\Data\Packages\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\Ai\Data\Packages\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\Ai\Data\Packages\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\Ai\Data\Packages\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 159, in adapter
new_model = model.clone()
File "D:\Ai\Data\Packages\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 228, in clip_vision_encode
elif t is not None:

**Comment by KINGLIFER** [comment]
Instant lora or reposer workflows

**Comment by nerdyrodent** [comment]
Open "ComfyUI Manager", click "Update All" and restart

**Comment by trashfiregoblin** [comment]
Getting the exact same error using the reposer plus workflow. fresh install yesterday.
![Screenshot 2023-10-29 184221](https://github.com/nerdyrodent/AVeryComfyNerd/assets/149343908/926396ea-a01e-41d8-885c-39c7820e077c)
 I just did the update all restart and still the same error.

**Comment by nerdyrodent** [comment]
> Getting the exact same error using the reposer plus workflow. fresh install yesterday. ![Screenshot 2023-10-29 184221](https://user-images.githubusercontent.com/149343908/278917195-926396ea-a01e-41d8-885c-39c7820e077c.png) I just did the update all restart and still the same error. Error occurred when executing IPAdapter:
> 
> Error(s) in loading state_dict for Resampler: size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).
> 
> File "C:\Users\F\Desktop\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\F\Desktop\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\F\Desktop\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\F\Desktop\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 142, in adapter self.ipadapter = IPAdapterModel( ^^^^^^^^^^^^^^^ File "C:\Users\F\Desktop\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 82, in **init** self.image_proj_model.load_state_dict(state_dict["image_proj"]) File "C:\Users\F\Desktop\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

While this doesn't look like the same error message, the issue here is that you need to use SD 1.5 models only - you can't mix SDXL & 1.5 in the workflow.
