### ISSUE TITLE
BatchPromptSchedule loading error

### ISSUE THREAD

**Issue by camaerart** [nerdyrodent/AVeryComfyNerd#2]
Hi, thanks for this tutorial, amazing content. btw im getting this errror : When loading the graph, the following node types were not found:
BatchPromptSchedule
Nodes that have failed to load will show as red on the graph.  the terminal output this : File "D:\ComfyUI-master\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-master\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import ValueSchedule, PromptSchedule, PromptScheduleNodeFlow, PromptScheduleNodeFlowEnd, PromptScheduleEncodeSDXL, StringSchedule, BatchPromptSchedule, BatchValueSchedule, BatchPromptScheduleEncodeSDXL
  File "D:\ComfyUI-master\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

Cannot import D:\ComfyUI-master\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'pandas'
Downloading anime face detector...
Failed to download lbpcascade_animeface.xml so please download it yourself.

**Comment by nerdyrodent** [comment]
Looks like some nodes haven't installed properly. Either install again using ComfyUI manager or manually.

**Comment by camaerart** [comment]
Yes, it was something related to that, for those who may have the same issue, try to reinstall from scratch comfy UI, and use not the portable version but the nerd installation ( using the terminal), it works for me now on a 3060 12gb .
