### ISSUE TITLE
Undefined Node

### ISSUE THREAD

**Issue by Grayjack64** [nerdyrodent/AVeryComfyNerd#4]
I'm trying to use the Reposer workflow. I've updated to the latest Comfy release and have gone through the process of Installing missing custom nodes. But I still get the following error:

![image](https://github.com/nerdyrodent/AVeryComfyNerd/assets/20065192/4fd8acbe-9cdc-434f-83ef-5c21d2b6e53a)

In the workflow it shows the following undefined node:

![image](https://github.com/nerdyrodent/AVeryComfyNerd/assets/20065192/db622fa8-330b-4f89-b34e-a570660356f3)

Any suggestions?

**Comment by nerdyrodent** [comment]
You'll need to install the IPAdapter custom node

**Comment by Grayjack64** [comment]
Thank you. The updates weren't taking for some reason so reinstalled and all works fine now.

**Comment by magejosh** [comment]
Latest release or latest git clone? Latest release looks like it was march 13. I went with git clone, but it seems something is still wrong for me on this particular issue. It's only in relation to IPAdapter-ComfyUI custom nodes.
