### ISSUE TITLE
'DwposeDetector' is not defined

### ISSUE THREAD

**Issue by Grayjack64** [nerdyrodent/AVeryComfyNerd#7]
I have updated Comfy and installed all of the missing plugins but now get the following error:

![image](https://github.com/nerdyrodent/AVeryComfyNerd/assets/20065192/0cc591ad-1faa-4893-8b1f-ca33426f6a4f)

My models are loaded as follows and I am bypassing the upsacling group:

![image](https://github.com/nerdyrodent/AVeryComfyNerd/assets/20065192/897d4ffd-734e-4782-aa95-338c24db9d9d)

**Comment by nerdyrodent** [comment]
The problem path is shown in the first image. Run 'git pull' in there to update the custom node to the current version - or update all in ComfyUI manager

**Comment by Grayjack64** [comment]
Thank you very much for your help. That worked.
