### ISSUE TITLE
PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8.

### ISSUE THREAD

**Issue by gigius** [nerdyrodent/AVeryComfyNerd#8]
Hello, thank you for all your content. Everything was working fine until yesterday but today I get this error when I try to create the animation:

PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8.

Do you know how I can solve this?
Thanks

**Comment by nerdyrodent** [comment]
While nothing to do with these workflows, it would appear you've mixed pytorch & torchvision versions up
