### ISSUE TITLE
 not found: CR Batch Process Switch

### ISSUE THREAD

**Issue by msskaa12** [nerdyrodent/AVeryComfyNerd#9]
appreciate for your awesome content, when I try this  workflow :
https://github.com/nerdyrodent/AVeryComfyNerd/blob/main/Reposer.png

I had some problem:

1 open this file in comfyui , it comes not found: CR Batch Process Switch

![new3](https://github.com/nerdyrodent/AVeryComfyNerd/assets/78275037/b5fb50c6-dd48-464f-b4fc-2ca573639297)

2 after I chose model ,and click the "queque prompt" , error message popup: SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)

![new2](https://github.com/nerdyrodent/AVeryComfyNerd/assets/78275037/ce42dcda-53c0-42fc-a239-ebab1499ddcd)

3 I had go to check the comfyui Manager to install missing custom node , it seems installed ,but still appear at missing list.I had try to reinstall ComfyUI_Comfyroll_CustomNodes , and restart comfyui , the error is comes again.

![e722d150-23a9-4129-8cec-078425bb2276](https://github.com/nerdyrodent/AVeryComfyNerd/assets/78275037/a60fce6f-20b6-4408-a4b5-30ed196c910e)

the error message in my terminal:

![new1](https://github.com/nerdyrodent/AVeryComfyNerd/assets/78275037/47035857-da34-49db-9ed8-9f095e549257)

I use a ubuntu machine  in conda enviroment:

![new4](https://github.com/nerdyrodent/AVeryComfyNerd/assets/78275037/98b13bf9-faad-42eb-afb2-73f9887f40d5)

**Comment by nerdyrodent** [comment]
CR Batch Process Switch is part of https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes
Be sure to update ComfyUI - including all custom nodes.

**Comment by msskaa12** [comment]
> CR Batch Process Switch is part of https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes Be sure to update ComfyUI - including all custom nodes.

I had update them all , may be the TensorrtExecutionProvider has not install correctly  ,I will track later.
![new5](https://github.com/nerdyrodent/AVeryComfyNerd/assets/78275037/eebc7fe8-3bfe-4e45-a7b5-8d013668a88a)

**Comment by nerdyrodent** [comment]
As a wild guess I'd suggest using a 3.10 environment over 3.8 - but that is just a guess. Your best bet is at [RockOfFire/ComfyUI_Comfyroll_CustomNodes](https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes).
